[package]
name = "big_brother"
version = "0.1.0"
authors = ["Dmitry Gordon <>"]

[dependencies]
telegram-bot = { git = "https://github.com/White-Oak/telegram-bot.git" }
mime = "*"
formdata = "*"
hyper = "0.10.8"
hyper-rustls = "0.3.2"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
